spring:
  application:
    name: rest-api-gateway
  cloud:
    config:
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
    gateway:
      routes:
      - id: product-route
        uri: http://localhost:9001
        predicates:
         - Path=/api/products/**
        filters:
        - name: CircuitBreaker
          args:
            name: productCircuitBreaker
            fallbackUri: forward:/product-fallback 
        
  security:
    oauth2:
      client:
        registration:
          product-portfolio:
            client-id: product-portfolio
            client-secret: zKDchvum8UZhj1TOBQLnyFfNiAUW8dje
            scope:
            - openid
            - profile
            - email     
        provider:
          product-portfolio:
            issuer-uri: http://localhost:8180/realms/product-portfolio
               
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
  timelimiter:
    configs:
      default:
        timeout-duration: 5s    
     
